"use client";
import { useEffect, useState } from "react";
import { addDoc, collection, getDocs } from "firebase/firestore";
import toast from "react-hot-toast";
import AppShell from "@/components/shells/AppShell";
import Card from "@/components/ui/Card";
import Button from "@/components/ui/Button";
import Spinner from "@/components/ui/Spinner";
import { db } from "@/lib/firebase";
import { useCurrentUser } from "@/lib/client-data";
import { courseFromDoc } from "@/lib/firestore-data";
import type { Course } from "@/types";
export default function AdminCoursesPage(){const {user,loading}=useCurrentUser();const [courses,setCourses]=useState<Course[]>([]);const [name,setName]=useState("");const [code,setCode]=useState("");const [caCeiling,setCaCeiling]=useState(30);const load=async()=>setCourses((await getDocs(collection(db,"courses"))).docs.map(courseFromDoc));useEffect(()=>{if(user?.role==="admin")load().catch(console.error);},[user]);if(loading||!user)return <div className="grid min-h-screen place-items-center"><Spinner/></div>;return <AppShell role={user.role} userName={user.displayName}><div className="mb-8"><p className="eyebrow">Registry workspace</p><h1 className="mt-1 font-display text-3xl font-bold tracking-tight">Course catalogue</h1><p className="mt-2 text-text-secondary">Set the CA ceiling and keep course records ready for assessment.</p></div><div className="grid gap-8 lg:grid-cols-[1fr_320px]"><div className="surface rounded-2xl p-5 sm:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-lg font-bold">Active courses</h2><span className="text-xs font-bold text-text-secondary">{courses.length} courses</span></div><div className="ledger">{courses.map(c=><div key={c.id} className="ledger-row flex items-center justify-between py-4"><div><p className="font-medium">{c.code}</p><p className="text-sm text-text-secondary">{c.name}</p></div><span className="font-tnum text-sm text-text-secondary">CA / {c.caCeiling}</span></div>)}</div></div><Card className="grid h-fit gap-3"><div><p className="font-display text-lg font-bold">Add a course</p><p className="mt-1 text-sm text-text-secondary">Make it available for assessment setup.</p></div><input className="min-h-12 rounded-lg border border-border px-3" placeholder="Course code (e.g. CSC301)" value={code} onChange={e=>setCode(e.target.value)}/><input className="min-h-12 rounded-lg border border-border px-3" placeholder="Course name" value={name} onChange={e=>setName(e.target.value)}/><label className="grid gap-1 text-sm">CA ceiling<input type="number" className="min-h-12 rounded-lg border border-border px-3" value={caCeiling} onChange={e=>setCaCeiling(Number(e.target.value))}/></label><Button onClick={async()=>{if(!name||!code){toast.error("Enter a course code and name.");return;}await addDoc(collection(db,"courses"),{name,code:code.toUpperCase(),caCeiling,lecturerId:""});setName("");setCode("");await load();toast.success("Course saved.");}}>Save course</Button></Card></div></AppShell>;}
