"use client";
import { useEffect, useState } from "react";
import { collection, getDoc, getDocs, doc } from "firebase/firestore";
import { useRouter } from "next/navigation";
import AppShell from "@/components/shells/AppShell";
import QuizCard from "@/components/molecules/QuizCard";
import Spinner from "@/components/ui/Spinner";
import { db } from "@/lib/firebase";
import { useCurrentUser } from "@/lib/client-data";
import { attemptFromData, courseFromDoc, quizFromDoc } from "@/lib/firestore-data";
import type { Attempt, Course, Quiz } from "@/types";
export default function StudentQuizzesPage(){const {user,loading}=useCurrentUser();const router=useRouter();const [courses,setCourses]=useState<Course[]>([]);const [quizzes,setQuizzes]=useState<Quiz[]>([]);const [attempts,setAttempts]=useState<Attempt[]>([]);useEffect(()=>{if(!user)return; if(user.role!=="student"){router.replace("/dashboard");return;} (async()=>{const [courseDocs,quizDocs]=await Promise.all([getDocs(collection(db,"courses")),getDocs(collection(db,"quizzes"))]);const qs=quizDocs.docs.map(quizFromDoc);setCourses(courseDocs.docs.map(courseFromDoc));setQuizzes(qs);const mine=await Promise.all(qs.map(async q=>{const snap=await getDoc(doc(db,"quizzes",q.id,"attempts",user.uid));return snap.exists()?attemptFromData(user.uid,q.id,snap.data()):null;}));setAttempts(mine.filter((a):a is Attempt=>a!==null));})().catch(console.error);},[user,router]);if(loading||!user)return <div className="grid min-h-screen place-items-center"><Spinner/></div>;const open=quizzes.filter(q=>q.startWindow<=Date.now()&&q.endWindow>=Date.now()).length;return <AppShell role={user.role} userName={user.displayName}><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Student workspace</p><h1 className="mt-1 font-display text-3xl font-bold tracking-tight">Your quizzes</h1><p className="mt-2 text-text-secondary">Pick up where you left off and keep an eye on what is next.</p></div><div className="surface rounded-2xl px-4 py-3"><p className="text-xs font-semibold uppercase tracking-wide text-text-secondary">Available now</p><p className="mt-1 text-2xl font-bold font-tnum text-primary">{open} <span className="text-sm font-medium text-text-secondary">open</span></p></div></div><section className="surface rounded-2xl p-5 sm:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-lg font-bold">Assessment schedule</h2><span className="text-xs font-semibold text-text-secondary">{quizzes.length} quizzes</span></div><div className="ledger">{quizzes.map(quiz=>{const course=courses.find(c=>c.id===quiz.courseId);const attempt=attempts.find(a=>a.quizId===quiz.id);return <QuizCard key={quiz.id} quiz={quiz} courseLabel={course?`${course.code} — ${course.name}`:""} ownScore={attempt?.score} maxScore={attempt?quiz.maxScore:undefined}/>;})}</div></section></AppShell>;}
